Heeblo/Controllers/ApplicationController.cs
using Heeblo.Models;
using Heeblo.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Heeblo.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class ApplicationController : ControllerBase
    {
        private readonly IApplication _app;

        public ApplicationController(IApplication app)
        {
            this._app = app;
        }
        [HttpGet]
        public IActionResult GetAllApplication()
        {
            var res = _app.GetAllApplication();
            return Ok(res);
        }
        [HttpGet]
        [HttpGet("{pid}")]
        public IActionResult GetApplicationByPid(int pid)
        {
            var res = _app.GetApplicationByPid(pid);
            return Ok(res);
        }

        [HttpGet]
        [HttpGet("{appId}")]
        public IActionResult GetUserDetailsByAppId(int appId)
        {
            var res = _app.GetUserDetailsByAppId(appId);
            return Ok(res);
        }
        [HttpGet("{id}")]
        public IActionResult GetApplicationById(int id)
        {
            var res = _app.GetApplicationById(id);
            return Ok(res);
        }
        [HttpPost]
        [HttpPost]
        public IActionResult ApplicationStatus(AppFeedback feedback)
        {
            var res = _app.ApplicationStatus(feedback);
            return Ok(res);
        }
        //[HttpGet("{pid}")]
        //public IActionResult GetAllAppCountByPid(int pid)
        //{
        //    var res = _app.GetAllAppCountByPid(pid);
        //    return Ok(res);
        //}
        [HttpPost]
        public IActionResult SaveApplication([FromForm] application_view app)
        {
            //var a = Request.Form.Files;
            var res = _app.SaveApplication(app);
            return Ok(res);
        }

    }
}

Heeblo/Controllers/HomeController.cs
using Heeblo.Models;
using Heeblo.Repository;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using System.Diagnostics;

namespace Heeblo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration configuration;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            this.configuration = configuration;
            _logger = logger;
        }
        public IActionResult AllUsers()
        {
            if (!Authorized(1)) return RedirectToAction("Login", "Auth");
            return View();
        }
        public IActionResult AdminProj()
        {
            if (!Authorized(1)) return RedirectToAction("Login", "Auth");
            return View();
        }
        public IActionResult PassResetSuc()
        {
            return View();
        }
        public IActionResult Verified()
        {
            return View();
        }
        public IActionResult EmailSent()
        {
            return View();
        }
        public IActionResult EmailSentReset()
        {
            return View();
        }

        public IActionResult WriterNoProject()
        {
            if (!Authorized(2)) return RedirectToAction("Login", "Auth");
            return View();
        }
        public IActionResult WriterThankyou()
        {
            HttpContext.Session.Clear();
            return View();
        }
        public IActionResult WriterUpload()
        {
            var user = HttpContext.Session.GetString("user")??null;
            if (!Authorized(2)) return RedirectToAction("Login", "Auth");
            return View();
        }
        public IActionResult Index()
        {
            if (!Authorized(3)) return RedirectToAction("Login", "Auth");
            return View();
        }

        public IActionResult Applications()
        {
            if (!Authorized(3)) return RedirectToAction("Login", "Auth");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Request(string pid)
        {
            var decryptedPid =  AESEncryption.Decrypt(pid);
            HttpContext.Session.SetObjectAsJson("pid", decryptedPid);
            return RedirectToAction("LoginSignUp", "Auth");
        }
        public IActionResult VerifyForReset(string uid)
        {
            var decryptedUid = AESEncryption.Decrypt(uid);

            var client = new RestClient(configuration["Config:API"]);
            var request = new RestRequest("User/VerifyUser/" + decryptedUid, Method.GET);
            var response = client.Execute<bool>(request).Data;
            if (response)
            {
                HttpContext.Session.SetObjectAsJson("uid", decryptedUid);
                return RedirectToAction("ResetPassword", "Auth");
            }
            else
            {
                return View("Login");
            }

        }
        public IActionResult Verify(string uid)
        {
            var decryptedUid = AESEncryption.Decrypt(uid);

            var client = new RestClient(configuration["Config:API"]);
            var request = new RestRequest("User/VerifyUser/"+ decryptedUid, Method.GET);
            var response = client.Execute<bool>(request).Data;
            if (response)
            {
                return RedirectToAction("Verified", "Home");
            }
            else
            {
                return View("Login");
            }

        }
        public bool Authorized(int role)
        {
            var serializedUser = HttpContext.Session.GetString("user") ?? null;
            if (serializedUser == null ) return false;
            var user = JsonConvert.DeserializeObject<hbl_tbl_user>(serializedUser);
            if (user.role != role) return false;
            return true;
        }
    }
}

Heeblo/Controllers/ProjectController.cs
using Heeblo.Models;
using Heeblo.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Heeblo.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class ProjectController : ControllerBase
    {
        private readonly IProject _proj;

        public ProjectController(IProject proj)
        {
            this._proj = proj;
        }
        [HttpGet("{uid}")]
        [HttpGet]
        public IActionResult GetAllProjects(int uid)
        {
            var res = _proj.GetAllProjects(uid);
            return Ok(res);
        }

        [HttpGet("{id}")]
        public IActionResult GetProjectById(int id)
        {
            var res = _proj.GetProjectById(id);
            return Ok(res);
        }
        [HttpPost]
        public IActionResult SaveProject(hbl_tbl_project proj)
        {
            var res = _proj.SaveProject(proj);
            return Ok(res);
        }
        
    }
}

Heeblo/Controllers/UserController.cs
using Heeblo.Implementation;
using Heeblo.Models;
using Heeblo.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Heeblo.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class UserController : ControllerBase
    {
        private readonly IUser _user;

        public UserController(IUser user)
        {
            this._user = user;
        }
        [HttpGet("{role?}")]
        public IActionResult GetAllUser(int role = 0)
        {
            var res = _user.GetAllUser(role);
            return Ok(res);
        }
        [HttpGet("{pid}")]
        public IActionResult GetUserByPublication(int pid)
        {
            var res = _user.GetUserByPublication(pid);
            return Ok(res);
        }
        [HttpGet("{id}")]
        public IActionResult GetUserById(int id)
        {
            var res = _user.GetUserById(id);
            return Ok(res);
        }
        [HttpPost]
        public IActionResult SaveUser(hbl_tbl_user user)
        {
            var res = _user.SaveUser(user);
            return Ok(res);
        }
        [HttpGet]
        [HttpGet("{userCred}")]
        public IActionResult ForgotLink(string userCred)
        {
           var resp= _user.ForgotLink(userCred);
            return Ok(resp);
        }
        [HttpGet]
        [HttpGet("{uid}/{password}")]
        public IActionResult PasswordForgot(int uid,string password)
        {
            var res = _user.PasswordForgot(uid,password);
            return Ok(res);
        }

        [HttpPost]
        public IActionResult ValidateUser(LoginReq req)
        {
            var resp = _user.ValidateUser(req);
            return Ok(resp);
        }
        [HttpGet("{uid}")]
        [HttpGet]
        public IActionResult VerifyUser(int uid)
        {
            var res = _user.VerifyUser(uid);
            return Ok(res);
        }
        [HttpGet("{uid}/{isActive}")]
        [HttpGet]
        public IActionResult ChangeIsActive(int uid, bool isActive)
        {
            var res = _user.ChangeIsActive(uid, isActive);
            return Ok(res);
        }

        [HttpGet("{encryptedData}")]
        public IActionResult Decrypt(string encryptedData)
        {
            var res = AESEncryption.Decrypt(encryptedData);
            return Ok(res);
        }
    }
}

Heeblo/Views/Home/AdminProj.cshtml
@using Microsoft.AspNetCore.Html
<style>
    .submittedBy {
        font-weight: bold;
        text-decoration: underline;
        cursor: pointer;
    }

    .fa-square-check {
        color: green;
    }

    .fa-circle-xmark {
        background-color: green;
    }
</style>
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <table id="tblProject" class="table table-sm table-striped table-bordered">
                    <thead>
                        <tr>
                            <th class="srnumber">Sr no</th>
                            <th>Project Name</th>
                            <th>Total Applications</th>
                            <th>Created On</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(function () {
            var params = new URLSearchParams(window.location.search)
            var uid = params.get('uid');
            GetAllProjects(uid);

        })
        function GetAllProjects(uid) {

            $('#tblProject').DataTable().destroy();
            $("#tblProject").dataTable({
                "ajax": {
                    url: '@(Url.Action("GetAllProjects", "Project"))' + '/' + uid,
                    type: "GET",
                    dataType: "JSON",
                    contentType: "application/json",
                    async: false,
                    dataSrc: ""
                },
                "columns": [
                    {
                        "targets": 0,
                        "render": function (data, type, row, meta) {
                            return meta.row + 1;
                        }
                    },
                    {
                        "data": "name"
                    },
                    { "data": "applicatant_count", },
                    {
                        "data": null,
                        "render": function (a, b, c) {
                            return moment(c.created_on).format("YYYY-MM-DD");
                        }
                    }

                ]
            })
        }

        
    </script>
}

Heeblo/Views/Home/AllUsers.cshtml
@using Microsoft.AspNetCore.Html
<style>
    .submittedBy {
        font-weight: bold;
        text-decoration: underline;
        cursor: pointer;
    }

    .fa-square-check {
        color: green;
    }

    .fa-circle-xmark {
        background-color: green;
    }
</style>

<div class="card">
    <div class="card-body">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <select id="ddlOptions" class="form-control form-control-sm" onchange="handleDropdownChange()">
                    <option value="3">Publisher</option>
                    <option value="2">Writer</option>
                </select>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-12">
                <table id="tblPublisher" class="table table-sm table-striped table-bordered">
                    <thead>
                        <tr>
                            <th class="srnumber">Sr no</th>
                            <th>Publisher</th>
                            <th>Created On</th>
                            <th>Is Active</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        var drpRole = 3
        $(document).ready(function () {
            GetAllPublisher();

        })
        function handleDropdownChange() {
            var selectedValue = document.getElementById("ddlOptions").value;
            drpRole = selectedValue;
            GetAllPublisher();
            console.log("Selected value:", drpRole);
            // Add your logic here
        }
        function GetAllPublisher() {

            $('#tblPublisher').DataTable().destroy();
            $("#tblPublisher").dataTable({
                "ajax": {
                    url: '@(Url.Action("GetAllUser", "User"))' + '/' + drpRole,
                    dataType: "JSON",
                    contentType: "application/json",
                    async: false,
                    dataSrc: ""
                },
                "columns": [
                    {
                        "targets": 0,
                        "render": function (data, type, row, meta) {
                            return meta.row + 1;
                        }
                    },
                    {
                        "data": null,
                        "render": function (a, b, c) {
                            return '<p class="submittedBy" onclick="viewProj(' + c.uid + ')">' + c.name + '</p>'
                        }
                    },
                    {
                        "data": null,
                        "render": function (a, b, c) {
                            return moment(c.created_on).format("YYYY-MM-DD");
                        }
                    },
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            return `<div class="form-check form-switch">
                                                            <input class="form-check-input" type="checkbox" role="switch" ${row.is_active ? 'checked' : ''} onclick="changeIsActive(this.checked,${row.uid})">
                                                            </div>`;
                        }
                    }

                ]
            })
        }
        function changeIsActive(isActive, uid) {
            console.log(isActive + uid)
            $.ajax({
                url: '@(Url.Action("ChangeIsActive", "user"))' + '/' + uid + '/' + isActive,
                type: "Get",
                contentType: "application/json",
                success: function (resp) {
                    (resp) ? Swal.fire('Updated successfully', '', 'success') : Swal.fire('Unable to update', '', 'error');
                    GetAllPublisher();

                },
                error: function (xhr, status, error) {
                    Swal.fire('Something went wrong', '', 'error');
                }
            });
        }
        function viewProj(uid) {
            if (drpRole == 2) return
            window.location.href = '@(Url.Action("AdminProj", "Home"))' + '?uid=' + uid
        }
    </script>
}

Heeblo/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Html
<style>
        .submittedBy {
        font-weight: bold;
        text-decoration: underline;
        cursor: pointer;
    }
    .fa-square-check {
        color: green;
    }

    .fa-circle-xmark {
        background-color: green;
    }
    @@media only screen and (max-width: 600px) {
        .icon-buttons{
            float: center !important;
        }
        table.dataTable thead th, table.dataTable tfoot th {
            padding: 12px 34px !important;
        }

    }
</style>
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12 table-responsive">
                <table id="tblProject" class="table table-sm table-striped table-bordered">
                    <thead>
                        <tr>
                            <th class="srnumber">Sr no</th>
                            <th>Project Name</th>
                            <th>Application Link</th>
                            <th>Share</th>
                            <th>Total Applications</th>
                            <th>Created On</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(function() {
            GetAllProjects(user.uid);

        })
        function GetAllProjects(uid) {

            $('#tblProject').DataTable().destroy();
            $("#tblProject").dataTable({
                "ajax": {
                    url: '@(Url.Action("GetAllProjects", "Project"))' + '/' + uid,
                    type: "GET",
                    dataType: "JSON",
                    contentType: "application/json",
                    async: false,
                    dataSrc: ""
                },
                "columns": [
                    {
                        "targets": 0,
                        "render": function(data, type, row, meta) {
                            return meta.row + 1;
                        }
                    },
                    {
                        "data": null,
                        "render": function(a, b, c) {
                            return '<p class="submittedBy" onclick="viewApplication(' + c.pid + ')">' + c.name + '</p>'
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row) {
                            var url = row.link;
                            var link = '<div class="link-container"><p title="' + url + '">' + row.name + '.heeblo.com</p></div>';
                            var copyButton = '<button class="btn btn-info btn-sm " onclick="share(\'copy\', \'' + row.link + '\')" title="Copy to Clipboard"><i class="far fa-copy"></i></button>';
                            return link + '<div class="icon-buttons">' + copyButton + '</div>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row) {
                            var whatsappButton = '<button class="btn btn-info btn-sm "  onclick="share(\'w\', \'' + row.link + '\')"><i class="fab fa-whatsapp"></i></button>';
                            var instagramButton = '<button class="btn btn-info btn-sm " onclick="share(\'i\', \'' + row.link + '\')"><i class="fab fa-instagram"></i></button>';
                            var twitterButton = '<button class="btn btn-info btn-sm "  onclick="share(\'t\', \'' + row.link + '\')"><i class="fab fa-twitter"></i></button>';
                            var linkedinButton = '<button class="btn btn-info btn-sm" onclick="share(\'l\', \'' + row.link + '\')"><i class="fab fa-linkedin"></i></button>';
                            return '<div class="icon-buttons">' + whatsappButton + ' ' + instagramButton + ' ' + twitterButton + ' ' + linkedinButton + '</div>';
                        }
                    },
                    { "data": "applicatant_count", },
                    {
                        "data": null,
                        "render": function(a, b, c) {
                            return moment(c.created_on).format("YYYY-MM-DD");
                        }
                    }

                ]
            })
        }
        function share(type, url) {

            switch (type) {
                case 'copy':
                    navigator.clipboard.writeText(url)
                        .then(function() {
                        })
                        .catch(function(error) {
                        });
                    break;
                case 'w':
                    var whatsappUrl = 'https://api.whatsapp.com/send?text=' + encodeURIComponent(url);
                    window.open(whatsappUrl, '_blank');
                    break;
                case 'i':
                    var instagramUrl = 'https://www.instagram.com/?url=' + encodeURIComponent(url);
                    window.open(instagramUrl, '_blank');
                    break;
                case 't':
                    var twitterUrl = 'https://twitter.com/intent/tweet?url=' + encodeURIComponent(url);
                    window.open(twitterUrl, '_blank');
                    break;
                case 'l':
                    var linkedinUrl = 'https://www.linkedin.com/shareArticle?url=' + encodeURIComponent(url);
                    window.open(linkedinUrl, '_blank');
                    break;
                default:
                    // Handle unknown social media platform
                    break;
            }
        }

        function viewApplication(pid) {
            window.location.href = '@(Url.Action("Applications","Home"))' + '?pid=' + pid
        }
    </script>
}

Heeblo/Views/Home/WriterUpload.cshtml
@using Microsoft.AspNetCore.Html
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- x-icon -->
    <link rel="shortcut icon" href="~/frontend-assets/pattern/assets/images/fav.png" type="image/x-icon">
    <!-- Other css -->
    <link rel="stylesheet" href="~/frontend-assets/pattern/assets/css/animate.css">
    <link rel="stylesheet" href="~/frontend-assets/pattern/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/frontend-assets/pattern/assets/css/all.min.css">
    <link rel="stylesheet" href="~/frontend-assets/pattern/assets/css/icofont.min.css">
    <link rel="stylesheet" href="~/frontend-assets/pattern/assets/css/swiper.min.css">
    <link rel="stylesheet" href="~/frontend-assets/pattern/assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        #files {
            position: absolute;
            left: 0;
            bottom: 0;
            opacity: 0;
        }

        .maximum.size p {
            text-align: center;
            color: #fff;
            font-size: 15px;
            font-weight: 500;
        }

        [type="file"] {
            display: none;
        }

        .button small {
            font-size: 0.6em;
        }
    </style>
</head>
<body>
    <div class="banner">
        <div class="container">
            <div class="content-login">
                @*<div class="top-logo">
                    <img src="~/frontend-assets/pattern/assets/images/heeblo-logo.png" alt="Logo">
                    </div>*@
                <div class="row" style="align-items: center;">
                    <div class="top-logo">  <img src="~/frontend-assets/pattern/assets/images/heeblo-logo.png" alt="Logo" /></div>

                    <div class="col-lg-6 col-md-6 main-form-center">

                        <div class="form-info wow fadeInDown" data-wow-duration="1.6s" style="visibility: visible; animation-duration: 1.6s; animation-name: fadeInDown;">
                            <div class="upload file">
                                <H3 style="text-align: center !important;color: #fff !important;">You're almost there </H3>
                            </div>
                            @*<div class="signup-line">
                                <a href="#">Or</a>
                                </div>*@
                            <div class="col-md-12 btn-login">
                                <div class="upload-btn">
                                    <label for="files" class="button">  Upload Resume<small><br /> Text here</small></label>
                                    <input id="resume" type="file">
                                </div>
                                <div class="upload-btn">
                                    <label for="files" class="button">  Upload Writing Sample<small><br /> Text here</small></label>
                                    <input id="sample" type="file">
                                </div>
                            </div>
                            <div class="maximum size">
                                <p> Max file size: 1 MB.</p> <p>Writing Sample ( Max 500 words )</p>
                            </div>
                            <span id="errorLabel" class="error-label"></span>
                            <br />
                            <button onclick="uploadFile()">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bottom-info">
        <div class="left-ft">
            <a href="mailto:admin@heeblo.com">
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                admin@heeblo.com
            </a>
        </div>
        <div class="right-ft">
            <ul>
                <li><a href="@Url.Action("termsandcondition","Auth")">Terms and Conditions </a></li>
                <li><a href="@Url.Action("privacypolicy","Auth")">Privacy Policy</a></li>
            </ul>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.js"></script>
    <script src="~/frontend-assets/pattern/assets/js/bootstrap.bundle.min.js"></script>
    <script src="~/frontend-assets/pattern/assets/js/waypoints.min.js"></script>
    <script src="~/frontend-assets/pattern/assets/js/swiper.min.js"></script>
    <script src="~/frontend-assets/pattern/assets/js/wow.min.js"></script>
    <script src="~/frontend-assets/pattern/assets/js/functions.js"></script>
</body>
<script>
    $('label[for="files"]').click(function() {
        $(this).parent().find('input[type="file"]').trigger('click');
    });

    $('input[type="file"]').change(function() {
        var f = $(this)[0].files;
        var maxSize = 1 * 1024 * 1024; // 1 MB in bytes
        var allowedTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];

        if (f.length == 0) {
            $(this).parent().find('.button small').empty();
        } else {
            var file = f[0];
            var fileSize = file.size;
            var fileType = file.type;

            if (fileSize <= maxSize && allowedTypes.includes(fileType)) {
                $(this).parent().find('.button small').html('<br/>' + file.name);
            } else {
                // Invalid file type or size exceeds the limit
                $(this).val(''); // Clear the selected file
                $(this).parent().find('.button small').empty();

                if (fileSize > maxSize) {
                $("#errorLabel").text('File size should be less than 1 MB.');
                } else {
                    $("#errorLabel").text('Only PDF, DOC, or DOCX files are allowed.');
                }
            }
        }
    }).trigger('change');



        function uploadFile() {
            var resumeFile = $("#resume").prop("files")[0];
            var sampleFile = $("#sample").prop("files")[0];

            if (!resumeFile || !sampleFile) {
                $("#errorLabel").text("Please upload both files.");
                return;
            }
            $("#errorLabel").text("");

            var user = @(new HtmlString(_hca.HttpContext.Session.GetString("user")??"null"));
            var pid = @(new HtmlString(_hca.HttpContext.Session.GetString("pid")??"null"));
            if(user=="null"||pid=="null"){
                        window.location.href = "@Url.Action("Login", "Auth")"
                        return;
            }

            var formData = new FormData()
            formData.append('resume', $('#resume')[0].files[0]);
            formData.append('sample_content', $('#sample')[0].files[0]);

            formData.append("pid", pid);
            formData.append("uid", user.uid);
            formData.append("created_by", user.uid);

            $.ajax({
                url: `@Url.Action("SaveApplication","Application")`,
                type: 'POST',
                data: formData,
                contentType: false,
                processData: false,
                success: function(resp) {
                    console.log(resp)
                    if (resp.resp) {
                        window.location.href = "@Url.Action("WriterThankyou", "Home")"
                    } else {
                        $("#errorLabel").text(resp.respMsg);
                    }
                },
                error: function(err) {
                    $("#errorLabel").text("Something went wrong .Please try again");
                }
            })
        }


</script>
</html>